export const killPatterns = [
    /(.+) was railed by (.+)/,
    /(.+) ate (.+?)'s rocket/,
    /(.+) was machinegunned by (.+)/,
    /(.+) was cut in half by (.+?)'s chaingun/,
    /(.+) almost dodged (.+?)'s rocket/,
    /(.+) was blown away by (.+?)'s super shotgun/,
    /(.+) was melted by (.+?)'s hyperblaster/,
    /(.+) saw the pretty lights from (.+?)'s BFG/,
    /(.+) was disintegrated by (.+?)'s BFG blast/,
    /(.+) was blasted by (.+)/,
    /(.+) was gunned down by (.+)/,
    /(.+) was popped by (.+?)'s grenade/,
    /(.+) was shredded by (.+?)'s shrapnel/,
    /(.+) caught (.+?)'s handgrenade/,
    /(.+) didn't see (.+?)'s handgrenade/,
    /(.+) feels (.+?)'s pain/,
    /(.+) tried to invade (.+?)'s personal space/,
    /(.+) couldn't hide from (.+?)'s BFG/
];
export const suicidePatterns = [
    /(.+) does a back flip into the lava/,
    /(.+) blew up/,
    /(.+) cratered/,
    /(.+) does a back flip into the lava/,
    /(.+) found a way out/,
    /(.+) got blasted/,
    /(.+) melted/,
    /(.+) sank like a rock/,
    /(.+) saw the light/,
    /(.+) suicides/,
    /(.+) was in the wrong place/,
    /(.+) was squished/,
    /(.+) blew herself up/,
    /(.+) blew himself up/,
    /(.+) blew itself up/,
    /(.+) killed herself/,
    /(.+) killed himself/,
    /(.+) killed itself/,
    /(.+) should have used a smaller gun/,
    /(.+) tried to put the pin back in/,
    /(.+) tripped on her own grenade/,
    /(.+) tripped on his own grenade/,
    /(.+) tripped on its own grenade/
];